### PR TITLE
"hint" -> "hints", remove displaystyle

### PR DESCRIPTION
**Pull request by lmffeexd**

### CODE REVIEW

**Comment by t-k-** [comment]
Hi, thanks for fixing this error from last commit. However, there are still some minor issues in this commit and I have further fixed:
1. There are some trailing spaces and spaces that are not aligned nicely.
2. You have to use double backslash to "escape" the single backslash into literal backslash. (See the other query examples, they are doing the same thing too)

Also, in case user thinks this is a math-only search engine, I prefer the demonstrated query to be mixed with both math expression and normal term instead of just one single math expression. Therefore I add another keyword "value" into the query.

So, I will close this PR and use the amended commit 6bb26fd0796b572e5cbfa05a5ba5c43a2dde21f5 instead.

**Comment by t-k-** [comment]
New code has been pulled to server.

**Comment by lmffeexd** [comment]
Thanks. Is there anyway by which you can enable `\displaystyle` for that?

**Comment by t-k-** [comment]
@lmffeexd Not really, I actually tried to do `\displaystyle` in "quiz" title, but since it does not fit into one line, the typeset when combining use it with typed.js looks really bad.

**Pull request closed without merging**
