### PR TITLE
Update quiz-list.js

### PR DESCRIPTION
**Pull request by lmffeexd**
Another question

### CODE REVIEW

**Comment by t-k-** [comment]
:+1: Thank you. I almost think in China we have two Internets, one is somewhat blocked, the other is local. (just joking)

**Comment by t-k-** [comment]
@lmffeexd I just pulled your code on server, make a hard refresh on Approach0.xyz and you will see your changes taking place.

**Comment by lmffeexd** [comment]
Thanks, I made two errors which I solved in this [other pull request](https://github.com/approach0/search-engine/pull/15).

**Comment by t-k-** [comment]
OK

**Pull request merged**
